-- =========================================================
-- Customer Shopping Behavior Analysis
-- Author: Harsh Patwa
-- Description: Business analysis using SQL
-- =========================================================

-- Preview Data
SELECT *
FROM customer
LIMIT 10;

-- =========================================================
-- Q1. What is the total revenue generated by male vs female customers?
-- =========================================================
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- =========================================================
-- Q2. Which customers used a discount but still spent more than
--     the average purchase amount?
-- =========================================================
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );

-- =========================================================
-- Q3. Which are the top 5 products with the highest
--     average review rating?
-- =========================================================
SELECT
    item_purchased,
    AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- =========================================================
-- Q4. Compare the average purchase amounts between
--     Standard and Express shipping.
-- =========================================================
SELECT
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- =========================================================
-- Q5. Do subscribed customers spend more?
--     Compare customer count, average spend, and total revenue
-- =========================================================
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    AVG(purchase_amount) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- =========================================================
-- Q6. Which 5 products have the highest percentage of
--     purchases with discounts applied?
-- =========================================================
SELECT
    item_purchased,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) 
        AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- =========================================================
-- Q7. Segment customers into New, Returning, and Loyal
--     based on previous purchases
-- =========================================================
SELECT
    CASE
        WHEN previous_purchases < 2 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;

-- =========================================================
-- Q8. What are the top 3 most purchased products
--     within each category?
-- =========================================================
WITH product_rank AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    total_orders
FROM product_rank
WHERE rank <= 3
ORDER BY category, total_orders DESC;

-- =========================================================
-- Q9. Are repeat buyers (more than 5 previous purchases)
--     also likely to subscribe?
-- =========================================================
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- =========================================================
-- Q10. What is the revenue contribution of each age group?
-- =========================================================
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
